name = "PhdCore"
version = "0.1.0"
defaultTargets = ["PhdCore"]

[[lean_lib]]
name = "PhdCore"

[[require]]
name = "aeneas"
git = "https://github.com/cryspen/aeneas"
rev = "nightly-2026.09.03-6852e64"
subDir = "backends/lean"

[[require]]
name = "Hax"
git = { url = "https://github.com/cryspen/hax-lean" }
rev = "v0.3.17"
