-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [phd_core]: function definitions
import Aeneas
import CoreModels
import PhdCore.Extraction.Types
import PhdCore.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace phd_core

/-- [phd_core::arithmetic::modulo::{phd_core::arithmetic::modulo::Ring}::new]:
    Source: 'crates/core/src/arithmetic/modulo.rs', lines 12:4-18:5 -/
def arithmetic.modulo.Ring.new
  (modulo : Std.U64) :
  RustM (core.result.Result arithmetic.modulo.Ring arithmetic.errors.RingError)
  := do
  if modulo = 0#u64
  then ok (core.result.Result.Err arithmetic.errors.RingError.ZeroModulo)
  else ok (core.result.Result.Ok { modulo })

end phd_core
