-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [phd_core]: type definitions
import Aeneas
import CoreModels
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace phd_core

/-- [phd_core::arithmetic::modulo::Ring]
    Source: 'crates/core/src/arithmetic/modulo.rs', lines 3:0-5:1 -/
structure arithmetic.modulo.Ring where
  modulo : Std.U64

/-- [phd_core::arithmetic::modulo::RingItem]
    Source: 'crates/core/src/arithmetic/modulo.rs', lines 7:0-7:32 -/
@[reducible]
def arithmetic.modulo.RingItem := Std.U64

end phd_core
